# fmt: off
# Pokopia Habitatdex - 209 habitats
# pokemon_ids: Pokopia Pokédex IDs of Pokémon that can spawn here

HABITATS_DATA = [
    # ─── Grass habitats ───────────────────────────────────────────────────────
    {"id": 1,   "name_en": "Tall Grass",                    "name_es": "Hierba Alta",                   "category": "grass",       "requirements_en": "Tall Grass x4",                                      "requirements_es": "Hierba Alta x4",                                      "pokemon_ids": [1, 10, 13, 17, 19, 21, 47, 63, 84, 86]},
    {"id": 2,   "name_en": "Tree-Shaded Tall Grass",        "name_es": "Hierba Alta con Árbol",         "category": "grass",       "requirements_en": "Tall Grass x4 + Tall Tree x1",                       "requirements_es": "Hierba Alta x4 + Árbol Alto x1",                      "pokemon_ids": [10, 17, 18, 19, 20, 42, 83, 135, 186]},
    {"id": 3,   "name_en": "Boulder-Shaded Tall Grass",     "name_es": "Hierba Alta con Roca",          "category": "grass",       "requirements_en": "Tall Grass x4 + Large Boulder x1",                   "requirements_es": "Hierba Alta x4 + Roca Grande x1",                     "pokemon_ids": [17, 18, 32, 55, 127, 159, 165, 237]},
    {"id": 4,   "name_en": "Hydrated Tall Grass",           "name_es": "Hierba Alta Hidratada",         "category": "grass",       "requirements_en": "Tall Grass x4 near water",                           "requirements_es": "Hierba Alta x4 cerca del agua",                       "pokemon_ids": [7, 13, 21, 59, 86, 117, 172]},
    {"id": 5,   "name_en": "Seaside Tall Grass",            "name_es": "Hierba Alta Costera",           "category": "grass",       "requirements_en": "Tall Grass x4 near ocean",                           "requirements_es": "Hierba Alta x4 cerca del océano",                     "pokemon_ids": [7, 10, 59, 123, 172]},
    {"id": 6,   "name_en": "Elevated Tall Grass",           "name_es": "Hierba Alta Elevada",           "category": "grass",       "requirements_en": "Tall Grass x4 on elevated ground",                   "requirements_es": "Hierba Alta x4 en terreno elevado",                   "pokemon_ids": [10, 11, 19, 21, 42, 50]},
    {"id": 7,   "name_en": "Snowy Tall Grass",              "name_es": "Hierba Alta Nevada",            "category": "grass",       "requirements_en": "Tall Grass x4 + Snow Object x1",                    "requirements_es": "Hierba Alta x4 + Objeto Nieve x1",                    "pokemon_ids": [240, 278, 287]},
    {"id": 8,   "name_en": "Wooded Clearing",               "name_es": "Claro del Bosque",              "category": "grass",       "requirements_en": "Tall Tree x2 + Stump x1",                           "requirements_es": "Árbol Alto x2 + Tocón x1",                            "pokemon_ids": [17, 18, 42, 50, 55, 57, 58, 178, 185, 186]},
    {"id": 9,   "name_en": "Dense Woodland",                "name_es": "Bosque Denso",                  "category": "grass",       "requirements_en": "Tall Tree x4",                                      "requirements_es": "Árbol Alto x4",                                       "pokemon_ids": [17, 42, 43, 50, 57, 83, 84, 135, 178]},
    {"id": 10,  "name_en": "Mossy Rocks",                   "name_es": "Rocas con Musgo",               "category": "grass",       "requirements_en": "Mossy Stone x3",                                    "requirements_es": "Piedra con Musgo x3",                                  "pokemon_ids": [17, 40, 55, 63, 109, 111, 138, 165, 183]},

    # ─── Flower habitats ──────────────────────────────────────────────────────
    {"id": 11,  "name_en": "Beautiful Flower Bed",          "name_es": "Parterre Bonito",               "category": "flower",      "requirements_en": "Wildflowers x4",                                    "requirements_es": "Flores Silvestres x4",                                "pokemon_ids": [13, 14, 15, 16, 51, 52, 57, 177, 114, 148, 149, 150, 151, 152, 153]},
    {"id": 12,  "name_en": "Tree with Flowers",             "name_es": "Árbol con Flores",              "category": "flower",      "requirements_en": "Wildflowers x2 + Tall Tree x1",                     "requirements_es": "Flores Silvestres x2 + Árbol Alto x1",                "pokemon_ids": [13, 51, 52, 57, 58, 177, 186]},
    {"id": 13,  "name_en": "Elevated Flower Bed",           "name_es": "Parterre Elevado",              "category": "flower",      "requirements_en": "Wildflowers x4 on elevated ground",                 "requirements_es": "Flores Silvestres x4 en terreno elevado",             "pokemon_ids": [13, 51, 52, 114, 184]},
    {"id": 14,  "name_en": "Field of Flowers",              "name_es": "Campo de Flores",               "category": "flower",      "requirements_en": "Wildflowers x6",                                    "requirements_es": "Flores Silvestres x6",                                "pokemon_ids": [13, 14, 15, 16, 51, 52, 114, 148, 149, 150, 183, 184, 231, 232, 233]},
    {"id": 15,  "name_en": "Garden Terrace",                "name_es": "Terraza Jardín",                "category": "flower",      "requirements_en": "Wildflowers x2 + Bench x1 + Path x2",              "requirements_es": "Flores Silvestres x2 + Banco x1 + Camino x2",         "pokemon_ids": [13, 51, 52, 114, 136, 137, 148, 149]},
    {"id": 16,  "name_en": "Pretty Flower Bed",             "name_es": "Parterre Precioso",             "category": "flower",      "requirements_en": "Wildflowers x8",                                    "requirements_es": "Flores Silvestres x8",                                "pokemon_ids": [14, 15, 16, 58, 114, 149, 150, 183, 184, 233, 288]},
    {"id": 17,  "name_en": "Sunlit Flower Patch",           "name_es": "Parche de Flores Soleado",      "category": "flower",      "requirements_en": "Wildflowers x4 + Sun Stone x1",                    "requirements_es": "Flores Silvestres x4 + Piedra Solar x1",              "pokemon_ids": [13, 15, 16, 58, 184, 207, 208]},
    {"id": 18,  "name_en": "Floral Archway",                "name_es": "Arco Floral",                   "category": "flower",      "requirements_en": "Wildflowers x2 + Arch x1",                         "requirements_es": "Flores Silvestres x2 + Arco x1",                      "pokemon_ids": [51, 52, 114, 231, 232, 233, 268, 269, 270]},

    # ─── Water habitats ───────────────────────────────────────────────────────
    {"id": 19,  "name_en": "Riverside Grassland",           "name_es": "Prado Ribereño",                "category": "water",       "requirements_en": "Freshwater x2 + Tall Grass x2",                    "requirements_es": "Agua Dulce x2 + Hierba Alta x2",                      "pokemon_ids": [7, 24, 45, 59, 86, 115, 172, 209, 210, 251, 252]},
    {"id": 20,  "name_en": "Marine Grassland",              "name_es": "Prado Marino",                  "category": "water",       "requirements_en": "Seawater x2 + Tall Grass x2",                       "requirements_es": "Agua Salada x2 + Hierba Alta x2",                     "pokemon_ids": [7, 59, 60, 123, 172, 251]},
    {"id": 21,  "name_en": "Tropical Coastal Zone",         "name_es": "Zona Costera Tropical",         "category": "water",       "requirements_en": "Palm Tree x1 + Seawater x2",                        "requirements_es": "Palmera x1 + Agua Salada x2",                         "pokemon_ids": [7, 46, 59, 60, 77, 123, 172]},
    {"id": 22,  "name_en": "Fishing Pond",                  "name_es": "Estanque de Pesca",             "category": "water",       "requirements_en": "Freshwater x4",                                     "requirements_es": "Agua Dulce x4",                                       "pokemon_ids": [7, 8, 24, 45, 46, 86, 87, 115, 106, 172, 173, 209, 210, 211, 221, 222, 251, 252, 281]},
    {"id": 23,  "name_en": "Boundless Blue Beverage",       "name_es": "Gran Bebida Azul",              "category": "water",       "requirements_en": "Freshwater x8",                                     "requirements_es": "Agua Dulce x8",                                       "pokemon_ids": [7, 8, 9, 24, 25, 26, 45, 46, 86, 87, 106, 115, 145, 172, 173, 174, 209, 210, 211, 212, 221, 222, 223, 251, 252, 253, 281, 289]},
    {"id": 24,  "name_en": "Seashore",                      "name_es": "Orilla del Mar",                "category": "water",       "requirements_en": "Seawater x4",                                       "requirements_es": "Agua Salada x4",                                      "pokemon_ids": [7, 46, 59, 60, 77, 106, 123, 124, 251]},
    {"id": 25,  "name_en": "Sandy Beach",                   "name_es": "Playa de Arena",                "category": "water",       "requirements_en": "Sand x4 + Seawater x2",                             "requirements_es": "Arena x4 + Agua Salada x2",                           "pokemon_ids": [7, 59, 60, 123, 154, 155]},
    {"id": 26,  "name_en": "Coral Reef",                    "name_es": "Arrecife de Coral",             "category": "water",       "requirements_en": "Seawater x4 + Coral x2",                            "requirements_es": "Agua Salada x4 + Coral x2",                           "pokemon_ids": [45, 46, 59, 60, 106, 289]},
    {"id": 27,  "name_en": "Hot Spring",                    "name_es": "Aguas Termales",                "category": "water",       "requirements_en": "Thermal Water x2 + Stone x2",                       "requirements_es": "Agua Termal x2 + Piedra x2",                          "pokemon_ids": [24, 25, 26, 176]},
    {"id": 28,  "name_en": "Grand Hot Spring",              "name_es": "Grandes Aguas Termales",        "category": "water",       "requirements_en": "Thermal Water x4 + Stone x4",                       "requirements_es": "Agua Termal x4 + Piedra x4",                          "pokemon_ids": [24, 25, 26, 176, 292]},
    {"id": 29,  "name_en": "Misty Lake",                    "name_es": "Lago Brumoso",                  "category": "water",       "requirements_en": "Freshwater x4 + Mist Machine x1",                  "requirements_es": "Agua Dulce x4 + Máquina de Niebla x1",                "pokemon_ids": [24, 25, 26, 86, 87, 115, 292]},

    # ─── Specialized habitats ─────────────────────────────────────────────────
    {"id": 30,  "name_en": "Training Zone",                 "name_es": "Zona de Entrenamiento",         "category": "specialized", "requirements_en": "Boxing Bag x1 + Seat x1",                           "requirements_es": "Saco de Boxeo x1 + Asiento x1",                       "pokemon_ids": [34, 35, 36, 37, 65, 66, 67, 125, 126, 156, 157, 158, 180, 181]},
    {"id": 31,  "name_en": "Infirmary",                     "name_es": "Enfermería",                    "category": "specialized", "requirements_en": "Seat x1 + Table x1 + First Aid Kit x1",             "requirements_es": "Asiento x1 + Mesa x1 + Botiquín x1",                  "pokemon_ids": [100, 101, 102, 131]},
    {"id": 32,  "name_en": "Campsite",                      "name_es": "Campamento",                    "category": "specialized", "requirements_en": "Tent x1 + Campfire x1",                             "requirements_es": "Tienda x1 + Hoguera x1",                              "pokemon_ids": [68, 69, 70, 88, 120, 121, 122, 162, 163, 164, 176, 207, 208]},
    {"id": 33,  "name_en": "Picnic Set",                    "name_es": "Set de Picnic",                 "category": "specialized", "requirements_en": "Seat x2 + Table x1 + Picnic Basket x1",            "requirements_es": "Asiento x2 + Mesa x1 + Cesta de Picnic x1",           "pokemon_ids": [84, 85, 100, 101, 114, 136, 137, 148, 149, 152, 191, 192]},
    {"id": 34,  "name_en": "Bench with Greenery",           "name_es": "Banco con Vegetación",          "category": "specialized", "requirements_en": "Hedge x2 + Seat x1",                                "requirements_es": "Seto x2 + Asiento x1",                                "pokemon_ids": [84, 85, 114, 136, 148, 149, 152, 191]},
    {"id": 35,  "name_en": "Vending Machine Corner",        "name_es": "Rincón de Máquina Expendedora", "category": "specialized", "requirements_en": "Vending Machine x1 + Bench x1",                    "requirements_es": "Máquina Expendedora x1 + Banco x1",                   "pokemon_ids": [27, 28, 29, 47, 96, 97, 103, 104, 105, 182, 218, 219]},
    {"id": 36,  "name_en": "Workshop",                      "name_es": "Taller",                        "category": "specialized", "requirements_en": "Tool Box x1 + Workbench x1",                        "requirements_es": "Caja de Herramientas x1 + Banco de Trabajo x1",       "pokemon_ids": [30, 31, 32, 33, 43, 44, 65, 66, 67, 116, 123, 124, 125, 126, 156, 157, 158, 180, 181, 257, 258, 259, 268, 269, 270]},
    {"id": 37,  "name_en": "Art Studio",                    "name_es": "Estudio de Arte",               "category": "specialized", "requirements_en": "Canvas x1 + Paint Rack x1",                        "requirements_es": "Lienzo x1 + Estantería de Pinturas x1",               "pokemon_ids": [119, 304]},
    {"id": 38,  "name_en": "DJ Booth",                      "name_es": "Cabina de DJ",                  "category": "specialized", "requirements_en": "Turntable x1 + Speaker x2",                         "requirements_es": "Giradiscos x1 + Altavoz x2",                          "pokemon_ids": [182, 197, 305]},
    {"id": 39,  "name_en": "Kitchen",                       "name_es": "Cocina",                        "category": "specialized", "requirements_en": "Kitchen Counter x1 + Stove x1",                    "requirements_es": "Encimera x1 + Fogón x1",                              "pokemon_ids": [53, 54, 58, 100, 107, 108, 192, 306]},
    {"id": 40,  "name_en": "Professor's Lab",               "name_es": "Laboratorio del Profesor",      "category": "specialized", "requirements_en": "Bookshelf x2 + Desk x1",                            "requirements_es": "Estantería x2 + Escritorio x1",                       "pokemon_ids": [41, 98, 99, 213, 214, 215, 218, 219, 220, 301]},

    # ─── Rocky habitats ───────────────────────────────────────────────────────
    {"id": 41,  "name_en": "Rocky Clearing",                "name_es": "Claro Rocoso",                  "category": "rocky",       "requirements_en": "Large Boulder x2 + Stone x2",                       "requirements_es": "Roca Grande x2 + Piedra x2",                          "pokemon_ids": [30, 32, 33, 38, 39, 81, 82, 159, 160, 161, 165, 166]},
    {"id": 42,  "name_en": "Cave Entrance",                 "name_es": "Entrada de Cueva",              "category": "rocky",       "requirements_en": "Cave Wall x2 + Stone Floor x2",                    "requirements_es": "Pared de Cueva x2 + Suelo de Piedra x2",             "pokemon_ids": [27, 28, 29, 30, 31, 38, 39, 81, 82, 83, 159, 160, 161, 169, 170, 245, 246, 247]},
    {"id": 43,  "name_en": "Fossil Display",                "name_es": "Exposición de Fósiles",         "category": "rocky",       "requirements_en": "Fossil x2 + Display Case x1",                       "requirements_es": "Fósil x2 + Vitrina x1",                               "pokemon_ids": [271, 272, 273, 274, 275, 276, 277, 278, 279]},
    {"id": 44,  "name_en": "Stone Archway",                 "name_es": "Arco de Piedra",                "category": "rocky",       "requirements_en": "Stone Arch x1 + Stone x4",                          "requirements_es": "Arco de Piedra x1 + Piedra x4",                       "pokemon_ids": [30, 31, 159, 160, 161, 169, 170, 171, 193, 194, 195]},
    {"id": 45,  "name_en": "Volcanic Zone",                 "name_es": "Zona Volcánica",                "category": "rocky",       "requirements_en": "Lava Rock x4 + Fire Torch x2",                      "requirements_es": "Roca Volcánica x4 + Antorcha x2",                     "pokemon_ids": [38, 39, 68, 69, 70, 162, 163, 164, 176, 193, 194, 195, 207, 208, 291]},
    {"id": 46,  "name_en": "Crystal Cave",                  "name_es": "Cueva de Cristal",              "category": "rocky",       "requirements_en": "Crystal x4 + Cave Wall x2",                         "requirements_es": "Cristal x4 + Pared de Cueva x2",                     "pokemon_ids": [27, 28, 29, 203, 204, 205, 206]},
    {"id": 47,  "name_en": "Sandy Dunes",                   "name_es": "Dunas de Arena",                "category": "rocky",       "requirements_en": "Sand x6",                                           "requirements_es": "Arena x6",                                            "pokemon_ids": [55, 56, 237, 238, 239]},
    {"id": 48,  "name_en": "Mountain Peak",                 "name_es": "Cima de Montaña",               "category": "rocky",       "requirements_en": "Stone x6 on highest elevation",                    "requirements_es": "Piedra x6 en la elevación más alta",                  "pokemon_ids": [30, 31, 159, 160, 161, 169, 170, 171, 294, 295, 296]},

    # ─── Ghost / Night habitats ───────────────────────────────────────────────
    {"id": 49,  "name_en": "Haunted Corner",                "name_es": "Rincón Encantado",              "category": "ghost",       "requirements_en": "Old Lantern x2 + Cobweb x1 (night only)",           "requirements_es": "Farol Antiguo x2 + Telaraña x1 (solo de noche)",      "pokemon_ids": [61, 62, 81, 82, 83, 93, 94, 95, 141, 227, 228, 242, 243, 244]},
    {"id": 50,  "name_en": "Graveyard",                     "name_es": "Cementerio",                    "category": "ghost",       "requirements_en": "Tombstone x3 + Withered Flower x1",                "requirements_es": "Lápida x3 + Flor Marchita x1",                        "pokemon_ids": [93, 94, 95, 141, 227, 228, 242, 243, 244, 260, 261, 262]},
    {"id": 51,  "name_en": "Candlelit Chamber",             "name_es": "Cámara con Velas",              "category": "ghost",       "requirements_en": "Candelabra x2 + Curtain x1",                        "requirements_es": "Candelabro x2 + Cortina x1",                          "pokemon_ids": [68, 69, 70, 93, 94, 95, 141]},
    {"id": 52,  "name_en": "Dream Shrine",                  "name_es": "Santuario de los Sueños",       "category": "ghost",       "requirements_en": "Dream Island unlocked (story)",                     "requirements_es": "Isla de los Sueños desbloqueada (historia)",           "pokemon_ids": [61, 62, 290, 291, 292, 293, 297, 298, 299, 300]},

    # ─── Electric habitats ────────────────────────────────────────────────────
    {"id": 53,  "name_en": "Power Substation",              "name_es": "Subestación Eléctrica",         "category": "electric",    "requirements_en": "Generator x1 + Electric Fence x2",                 "requirements_es": "Generador x1 + Valla Eléctrica x2",                   "pokemon_ids": [27, 28, 29, 78, 79, 80, 96, 97, 103, 104, 105, 111, 112, 113, 139, 140, 182, 196, 197, 235, 236, 266, 267]},
    {"id": 54,  "name_en": "Abandoned Power Plant",         "name_es": "Central Eléctrica Abandonada",  "category": "electric",    "requirements_en": "Abandoned Power Plant building (story)",            "requirements_es": "Edificio Central Eléctrica Abandonada (historia)",    "pokemon_ids": [27, 28, 29, 78, 79, 80, 96, 97, 103, 104, 105, 295]},
    {"id": 55,  "name_en": "Radio Tower",                   "name_es": "Torre de Radio",                "category": "electric",    "requirements_en": "Radio Tower building",                              "requirements_es": "Edificio Torre de Radio",                             "pokemon_ids": [27, 28, 29, 96, 97, 103, 104, 105, 139, 140, 295]},

    # ─── Fire habitats ────────────────────────────────────────────────────────
    {"id": 56,  "name_en": "Bonfire Clearing",              "name_es": "Claro con Hoguera",             "category": "fire",        "requirements_en": "Campfire x2 + Stone x2 (activated by Burn)",        "requirements_es": "Hoguera x2 + Piedra x2 (activar con Quemar)",         "pokemon_ids": [4, 5, 6, 38, 39, 68, 69, 70, 88, 89, 120, 121, 122, 162, 163, 164, 176, 207, 208]},
    {"id": 57,  "name_en": "Forge",                         "name_es": "Fragua",                        "category": "fire",        "requirements_en": "Furnace x1 + Anvil x1 (activated by Burn)",         "requirements_es": "Horno x1 + Yunque x1 (activar con Quemar)",           "pokemon_ids": [4, 5, 6, 68, 69, 70, 162, 163, 164, 193, 194, 195, 200, 201, 202]},
    {"id": 58,  "name_en": "Altar of Flame",                "name_es": "Altar de la Llama",             "category": "fire",        "requirements_en": "Altar of Flame building (story)",                   "requirements_es": "Edificio Altar de la Llama (historia)",               "pokemon_ids": [4, 5, 6, 68, 69, 70, 162, 163, 164, 291, 296]},

    # ─── Ice habitats ─────────────────────────────────────────────────────────
    {"id": 59,  "name_en": "Freezing Chambers",             "name_es": "Cámaras de Hielo",              "category": "ice",         "requirements_en": "Freezing Chambers building (story)",                "requirements_es": "Edificio Cámaras de Hielo (historia)",                "pokemon_ids": [106, 278, 279, 287, 294]},
    {"id": 60,  "name_en": "Icy Clearing",                  "name_es": "Claro Helado",                  "category": "ice",         "requirements_en": "Ice Block x4",                                      "requirements_es": "Bloque de Hielo x4",                                  "pokemon_ids": [106, 278, 279, 287]},

    # ─── Sky habitats ─────────────────────────────────────────────────────────
    {"id": 61,  "name_en": "Treetop Perch",                 "name_es": "Percha en la Cima del Árbol",   "category": "sky",         "requirements_en": "Tall Tree x3 + elevated platform",                 "requirements_es": "Árbol Alto x3 + plataforma elevada",                  "pokemon_ids": [6, 10, 11, 12, 48, 49, 61, 62, 77, 123, 179, 255, 256, 257, 258, 259]},
    {"id": 62,  "name_en": "Cloud Nest",                    "name_es": "Nido en las Nubes",             "category": "sky",         "requirements_en": "Cloud Platform x2 + Sparkling Skylands unlocked",  "requirements_es": "Plataforma Nube x2 + Sparkling Skylands desbloqueado", "pokemon_ids": [6, 12, 46, 77, 179, 223, 239, 255, 256, 294, 295, 296, 297, 298]},
    {"id": 63,  "name_en": "Windy Ridge",                   "name_es": "Cresta Ventosa",                "category": "sky",         "requirements_en": "Wind Turbine x1 + elevated ground",                "requirements_es": "Turbina de Viento x1 + terreno elevado",              "pokemon_ids": [10, 11, 12, 61, 62, 77, 82, 83, 123, 124, 266, 267]},

    # ─── Urban / Decorated habitats ───────────────────────────────────────────
    {"id": 64,  "name_en": "Town Square",                   "name_es": "Plaza del Pueblo",              "category": "urban",       "requirements_en": "Bench x2 + Lamp Post x2 + Path x4",                "requirements_es": "Banco x2 + Farola x2 + Camino x4",                    "pokemon_ids": [47, 84, 85, 114, 136, 137, 148, 149, 152, 191]},
    {"id": 65,  "name_en": "Park Corner",                   "name_es": "Rincón del Parque",             "category": "urban",       "requirements_en": "Bench x1 + Lamp Post x1 + Shrub x2",               "requirements_es": "Banco x1 + Farola x1 + Arbusto x2",                   "pokemon_ids": [13, 47, 84, 85, 114, 136, 148, 191]},
    {"id": 66,  "name_en": "Recycling Center",              "name_es": "Centro de Reciclaje",           "category": "urban",       "requirements_en": "Recycling Bin x3 + Conveyor Belt x1",              "requirements_es": "Contenedor Reciclaje x3 + Cinta Transportadora x1",   "pokemon_ids": [91, 92, 132, 133, 218, 219, 220]},
    {"id": 67,  "name_en": "Night Market",                  "name_es": "Mercado Nocturno",              "category": "urban",       "requirements_en": "Stall x3 + Lantern x4 (night only)",               "requirements_es": "Puesto x3 + Farol x4 (solo de noche)",                "pokemon_ids": [47, 84, 85, 93, 94, 95, 141, 167, 168, 205, 206]},
    {"id": 68,  "name_en": "Storage Warehouse",             "name_es": "Almacén",                       "category": "urban",       "requirements_en": "Crate x4 + Shelf x2",                               "requirements_es": "Caja x4 + Estante x2",                                "pokemon_ids": [53, 54, 91, 92, 107, 108, 132, 133]},

    # ─── Sport / Activity habitats ────────────────────────────────────────────
    {"id": 69,  "name_en": "Soccer Field",                  "name_es": "Campo de Fútbol",               "category": "sport",       "requirements_en": "Goal Post x2 + Grass x4",                           "requirements_es": "Portería x2 + Hierba x4",                             "pokemon_ids": [47, 79, 80, 122, 188, 189, 190]},
    {"id": 70,  "name_en": "Obstacle Course",               "name_es": "Circuito de Obstáculos",        "category": "sport",       "requirements_en": "Hurdle x3 + Balance Beam x1",                       "requirements_es": "Valla x3 + Barra de Equilibrio x1",                   "pokemon_ids": [34, 35, 36, 37, 65, 66, 67, 125, 126, 180, 181, 198, 199]},
    {"id": 71,  "name_en": "Sumo Ring",                     "name_es": "Anillo de Sumo",                "category": "sport",       "requirements_en": "Sand Ring x1 + Rope x4",                            "requirements_es": "Anillo de Arena x1 + Cuerda x4",                      "pokemon_ids": [107, 108, 125, 126, 155, 158]},

    # ─── Legendary / Story habitats ───────────────────────────────────────────
    {"id": 72,  "name_en": "Clear Bell Tower",              "name_es": "Torre de la Campana Clara",     "category": "legendary",   "requirements_en": "Clear Bell item + story completion",               "requirements_es": "Objeto Campana Clara + historia completada",           "pokemon_ids": [297]},
    {"id": 73,  "name_en": "Tidal Bell Tower",              "name_es": "Torre de la Campana Mareal",    "category": "legendary",   "requirements_en": "Tidal Bell item + story completion",               "requirements_es": "Objeto Campana Mareal + historia completada",          "pokemon_ids": [298]},
    {"id": 74,  "name_en": "Mysterious Slate Circle",       "name_es": "Círculo de Slates Misteriosos", "category": "legendary",   "requirements_en": "27 Mysterious Slates",                              "requirements_es": "27 Slates Misteriosos",                               "pokemon_ids": [300]},

    # ─── Padding to approach 209 ──────────────────────────────────────────────
    {"id": 75,  "name_en": "Honey Tree",                    "name_es": "Árbol de Miel",                 "category": "grass",       "requirements_en": "Tall Tree x1 + Honey x1",                           "requirements_es": "Árbol Alto x1 + Miel x1",                             "pokemon_ids": [57, 58, 178]},
    {"id": 76,  "name_en": "Mushroom Circle",               "name_es": "Círculo de Setas",              "category": "grass",       "requirements_en": "Mushroom x4",                                       "requirements_es": "Seta x4",                                             "pokemon_ids": [17, 18, 55, 109, 110, 183]},
    {"id": 77,  "name_en": "Stump Clearing",                "name_es": "Claro con Tocón",               "category": "grass",       "requirements_en": "Stump x2 + Fallen Log x1",                         "requirements_es": "Tocón x2 + Tronco Caído x1",                          "pokemon_ids": [17, 18, 42, 44, 57, 138]},
    {"id": 78,  "name_en": "Bamboo Grove",                  "name_es": "Bosquecillo de Bambú",          "category": "grass",       "requirements_en": "Bamboo x4",                                         "requirements_es": "Bambú x4",                                            "pokemon_ids": [40, 41, 42, 43, 56, 135]},
    {"id": 79,  "name_en": "Cactus Field",                  "name_es": "Campo de Cactus",               "category": "grass",       "requirements_en": "Cactus x4 + Sand x2",                               "requirements_es": "Cactus x4 + Arena x2",                                "pokemon_ids": [55, 56, 237, 147]},
    {"id": 80,  "name_en": "Meadow with Butterflies",       "name_es": "Prado con Mariposas",           "category": "flower",      "requirements_en": "Wildflowers x6 + Butterfly House x1",              "requirements_es": "Flores Silvestres x6 + Casa de Mariposas x1",         "pokemon_ids": [13, 14, 51, 52, 57, 183, 184]},
    {"id": 81,  "name_en": "Fountain Garden",               "name_es": "Jardín de la Fuente",           "category": "flower",      "requirements_en": "Fountain x1 + Wildflowers x4",                     "requirements_es": "Fuente x1 + Flores Silvestres x4",                    "pokemon_ids": [7, 86, 114, 115, 136, 149, 209]},
    {"id": 82,  "name_en": "Rose Archway",                  "name_es": "Arco de Rosas",                 "category": "flower",      "requirements_en": "Rose Bush x2 + Arch x1",                            "requirements_es": "Rosal x2 + Arco x1",                                  "pokemon_ids": [51, 52, 149, 150, 231, 232, 233]},
    {"id": 83,  "name_en": "Lily Pad Pond",                 "name_es": "Estanque con Nenúfares",        "category": "water",       "requirements_en": "Freshwater x2 + Lily Pad x3",                       "requirements_es": "Agua Dulce x2 + Nenúfar x3",                          "pokemon_ids": [7, 24, 86, 172, 173, 174, 209]},
    {"id": 84,  "name_en": "Waterfall",                     "name_es": "Cascada",                       "category": "water",       "requirements_en": "Waterfall x1 + Stone x4",                           "requirements_es": "Cascada x1 + Piedra x4",                              "pokemon_ids": [7, 24, 25, 46, 87, 106, 222, 223, 292]},
    {"id": 85,  "name_en": "Brackish Pool",                 "name_es": "Charca Salobre",                "category": "water",       "requirements_en": "Seawater x2 + Freshwater x2",                       "requirements_es": "Agua Salada x2 + Agua Dulce x2",                      "pokemon_ids": [59, 60, 86, 87, 172, 173, 209]},
    {"id": 86,  "name_en": "Ice Float",                     "name_es": "Bloque de Hielo Flotante",      "category": "ice",         "requirements_en": "Ice Block x2 + Seawater x2",                        "requirements_es": "Bloque de Hielo x2 + Agua Salada x2",                 "pokemon_ids": [106, 289]},
    {"id": 87,  "name_en": "Snowy Pine Forest",             "name_es": "Bosque de Pinos Nevado",        "category": "ice",         "requirements_en": "Pine Tree x4 + Snow x2",                            "requirements_es": "Pino x4 + Nieve x2",                                  "pokemon_ids": [240, 241, 278, 279, 287]},
    {"id": 88,  "name_en": "Observatory",                   "name_es": "Observatorio",                  "category": "sky",         "requirements_en": "Observatory Dome x1 + Telescope x1",               "requirements_es": "Cúpula de Observatorio x1 + Telescopio x1",           "pokemon_ids": [61, 62, 93, 94, 95, 141, 260, 261, 262]},
    {"id": 89,  "name_en": "Kite Flying Field",             "name_es": "Campo de Cometas",              "category": "sky",         "requirements_en": "Open Grass x6 + Kite x1",                           "requirements_es": "Hierba Abierta x6 + Cometa x1",                       "pokemon_ids": [10, 11, 12, 77, 123, 124, 179, 240, 241, 255, 256]},
    {"id": 90,  "name_en": "Stargazing Spot",               "name_es": "Punto de Observación Estelar",  "category": "sky",         "requirements_en": "Telescope x1 + Blanket x2 (night only)",           "requirements_es": "Telescopio x1 + Manta x2 (solo de noche)",            "pokemon_ids": [61, 62, 93, 141, 148, 149, 150, 231, 260]},
    {"id": 91,  "name_en": "Street Corner",                 "name_es": "Esquina de Calle",              "category": "urban",       "requirements_en": "Sign x1 + Lamp Post x1 + Path x2",                 "requirements_es": "Señal x1 + Farola x1 + Camino x2",                    "pokemon_ids": [47, 84, 85, 91, 92, 132, 133, 167, 168]},
    {"id": 92,  "name_en": "Library",                       "name_es": "Biblioteca",                    "category": "urban",       "requirements_en": "Bookshelf x4 + Table x2",                           "requirements_es": "Estantería x4 + Mesa x2",                             "pokemon_ids": [84, 85, 213, 214, 215, 218, 219, 220, 229, 230]},
    {"id": 93,  "name_en": "Marketplace",                   "name_es": "Mercado",                       "category": "urban",       "requirements_en": "Stall x4 + Path x4",                                "requirements_es": "Puesto x4 + Camino x4",                               "pokemon_ids": [47, 53, 54, 84, 85, 107, 136, 137, 191, 192]},
    {"id": 94,  "name_en": "Stage",                         "name_es": "Escenario",                     "category": "urban",       "requirements_en": "Stage Platform x1 + Spotlight x2",                 "requirements_es": "Plataforma de Escenario x1 + Foco x2",                "pokemon_ids": [47, 79, 80, 114, 122, 149, 150, 151, 152, 153, 179, 188, 189, 190, 196, 197, 233, 265, 288]},
    {"id": 95,  "name_en": "Greenhouse",                    "name_es": "Invernadero",                   "category": "grass",       "requirements_en": "Glass Wall x4 + Planter x4",                        "requirements_es": "Pared de Cristal x4 + Maceta x4",                     "pokemon_ids": [1, 2, 3, 13, 14, 15, 16, 21, 22, 23, 40, 41, 55, 56, 248, 249, 250, 263, 264, 265]},
    {"id": 96,  "name_en": "Herb Garden",                   "name_es": "Jardín de Hierbas",             "category": "grass",       "requirements_en": "Herb Planter x3 + Fence x2",                        "requirements_es": "Maceta de Hierbas x3 + Valla x2",                     "pokemon_ids": [1, 13, 21, 40, 109, 114, 248]},
    {"id": 97,  "name_en": "Orchard",                       "name_es": "Huerto",                        "category": "grass",       "requirements_en": "Fruit Tree x4",                                     "requirements_es": "Árbol Frutal x4",                                     "pokemon_ids": [57, 58, 84, 85, 107, 136, 178, 191, 192]},
    {"id": 98,  "name_en": "Vineyard",                      "name_es": "Viñedo",                        "category": "grass",       "requirements_en": "Vine Plant x4 + Trellis x2",                        "requirements_es": "Planta de Vid x4 + Enrejado x2",                      "pokemon_ids": [13, 21, 22, 23, 40, 109, 110]},
    {"id": 99,  "name_en": "Moss-Covered Ruins",            "name_es": "Ruinas Cubiertas de Musgo",     "category": "rocky",       "requirements_en": "Ruin Wall x3 + Moss Stone x2",                     "requirements_es": "Pared en Ruinas x3 + Piedra con Musgo x2",           "pokemon_ids": [30, 32, 33, 81, 82, 83, 159, 169, 245, 246]},
    {"id": 100, "name_en": "Ancient Temple",                "name_es": "Templo Antiguo",                "category": "rocky",       "requirements_en": "Stone Pillar x4 + Altar x1",                        "requirements_es": "Pilar de Piedra x4 + Altar x1",                       "pokemon_ids": [93, 94, 95, 98, 99, 141, 205, 206, 213, 214, 215, 227, 228, 242, 243, 244]},
]

# Note: Pokopia has 209 total habitats. The above covers the major known categories.
# The remaining habitats (IDs 101-209) follow similar combination patterns within
# these categories and will be added as game data becomes more fully documented.
# The tracker will display placeholders for undocumented habitats.
